import type { FeatureNav } from "@/lib/nav/types";

/**
 * TRANSITIONAL — nav entries whose feature folders do not yet exist.
 * Items migrate out of this file into `src/features/<feature>/nav.ts`
 * as each real feature is built in Phases 5–9 per ADR-0004. The
 * `rbac:pending-empty` CI gate fails any merge to main once Phase 9
 * completes if this array is non-empty.
 *
 * Visibility semantics replicate `src/lib/rbac/sidebar-config.ts` + the
 * persona split in `src/lib/rbac/navigation.ts#adminNavManifest`:
 *   - IT Admin persona: holds `it:c` OR `system:c` → sees IT section.
 *   - Business Admin persona: holds neither → sees Business section.
 * Implemented via per-item `excludeWhenHoldsAnyDomain` on Business items.
 */
const IT_PERSONA_DOMAINS = [
  { domain: "it", access: "c" },
  { domain: "system", access: "c" },
] as const;

export const nav: FeatureNav = {
  featureId: "_pending",
  items: [
    // ── Admin · IT section ──
    {
      id: "admin-it",
      portal: "admin",
      path: "/admin/it",
      section: "it",
      order: 10,
      iconName: "LayoutDashboard",
      labelKey: "nav.admin.dashboard",
      label: "Dashboard",
      requires: { domain: "it", access: "c" },
    },
    {
      id: "admin-iam",
      portal: "admin",
      path: "/admin/iam",
      section: "it",
      order: 20,
      iconName: "ScrollText",
      labelKey: "nav.admin.iam",
      label: "IAM Ledger",
      requires: { domain: "hr", access: "c" },
    },
    {
      id: "admin-devices",
      portal: "admin",
      path: "/admin/devices",
      section: "it",
      order: 30,
      iconName: "Monitor",
      labelKey: "nav.admin.devices",
      label: "Devices",
      requires: { domain: "it", access: "c" },
    },
    {
      id: "admin-system-health",
      portal: "admin",
      path: "/admin/system-health",
      section: "it",
      order: 40,
      iconName: "Activity",
      labelKey: "nav.admin.systemHealth",
      label: "System Health",
      requires: { domain: "it", access: "c" },
    },
    {
      id: "admin-zones",
      portal: "admin",
      path: "/admin/zones",
      section: "it",
      order: 50,
      iconName: "MapPin",
      labelKey: "nav.admin.zones",
      label: "Zones & Locations",
      requires: { domain: "system", access: "c" },
    },
    {
      id: "admin-org-units",
      portal: "admin",
      path: "/admin/org-units",
      section: "it",
      order: 60,
      iconName: "Boxes",
      labelKey: "nav.admin.orgUnits",
      label: "Org Units",
      requires: { domain: "system", access: "c" },
    },
    {
      id: "admin-permissions",
      portal: "admin",
      path: "/admin/permissions",
      section: "it",
      order: 70,
      iconName: "ShieldCheck",
      labelKey: "nav.admin.permissions",
      label: "Permissions",
      requires: { domain: "system", access: "c" },
    },
    {
      id: "admin-units",
      portal: "admin",
      path: "/admin/units",
      section: "it",
      order: 80,
      iconName: "Ruler",
      labelKey: "nav.admin.units",
      label: "Units of Measure",
      requires: { domain: "system", access: "c" },
    },

    // ── Admin · Business section (hidden from IT-persona users) ──
    {
      id: "admin-business",
      portal: "admin",
      path: "/admin/business",
      section: "business",
      order: 10,
      iconName: "LayoutDashboard",
      labelKey: "nav.admin.dashboard",
      label: "Dashboard",
      requires: { domain: "booking", access: "r" },
      excludeWhenHoldsAnyDomain: IT_PERSONA_DOMAINS,
    },
    {
      id: "admin-revenue",
      portal: "admin",
      path: "/admin/revenue",
      section: "business",
      order: 20,
      iconName: "LineChart",
      labelKey: "nav.admin.revenue",
      label: "Revenue",
      requires: { domain: "booking", access: "r" },
      excludeWhenHoldsAnyDomain: IT_PERSONA_DOMAINS,
    },
    {
      id: "admin-operations",
      portal: "admin",
      path: "/admin/operations",
      section: "business",
      order: 30,
      iconName: "Settings",
      labelKey: "nav.admin.operations",
      label: "Operations",
      requires: { domain: "ops", access: "r" },
      excludeWhenHoldsAnyDomain: IT_PERSONA_DOMAINS,
    },
    {
      id: "admin-costs",
      portal: "admin",
      path: "/admin/costs",
      section: "business",
      order: 40,
      iconName: "Wallet",
      labelKey: "nav.admin.costs",
      label: "Costs",
      requires: { domain: "inventory", access: "r" },
      excludeWhenHoldsAnyDomain: IT_PERSONA_DOMAINS,
    },
    {
      id: "admin-guests",
      portal: "admin",
      path: "/admin/guests",
      section: "business",
      order: 50,
      iconName: "Users",
      labelKey: "nav.admin.guests",
      label: "Guests",
      requires: { domain: "reports", access: "r" },
      excludeWhenHoldsAnyDomain: IT_PERSONA_DOMAINS,
    },
    {
      id: "admin-workforce",
      portal: "admin",
      path: "/admin/workforce",
      section: "business",
      order: 60,
      iconName: "Users",
      labelKey: "nav.admin.workforce",
      label: "Workforce",
      requires: { domain: "hr", access: "r" },
      excludeWhenHoldsAnyDomain: IT_PERSONA_DOMAINS,
    },

    // ── Admin · Shared section ──
    {
      id: "admin-reports",
      portal: "admin",
      path: "/admin/reports",
      section: "shared",
      order: 10,
      iconName: "FileText",
      labelKey: "nav.admin.reports",
      label: "Reports",
      requires: { domain: "reports", access: "r" },
    },
    {
      id: "admin-audit",
      portal: "admin",
      path: "/admin/audit",
      section: "shared",
      order: 20,
      iconName: "History",
      labelKey: "nav.admin.audit",
      label: "Audit Log",
      requires: { domain: "reports", access: "r" },
    },
    {
      id: "admin-announcements",
      portal: "admin",
      path: "/admin/announcements",
      section: "shared",
      order: 30,
      iconName: "Megaphone",
      labelKey: "nav.admin.announcements",
      label: "Announcements",
      requires: { domain: "comms", access: "r" },
    },
    // admin-attendance → owned by src/features/attendance/nav.ts
    {
      id: "admin-settings",
      portal: "admin",
      path: "/admin/settings",
      section: "shared",
      order: 50,
      iconName: "Settings",
      labelKey: "nav.admin.settings",
      label: "Settings",
      // Always visible: no `requires`.
    },

    // ── Management · Domains section ──
    {
      id: "mgmt-hr",
      portal: "management",
      path: "/management/hr",
      section: "domains",
      order: 10,
      iconName: "Users",
      labelKey: "nav.mgmt.hr",
      label: "HR",
      requires: { domain: "hr", access: "c" },
    },
    {
      id: "mgmt-pos",
      portal: "management",
      path: "/management/pos",
      section: "domains",
      order: 20,
      iconName: "CreditCard",
      labelKey: "nav.mgmt.pos",
      label: "POS",
      requires: { domain: "pos", access: "c" },
    },
    {
      id: "mgmt-inventory",
      portal: "management",
      path: "/management/inventory",
      section: "domains",
      order: 30,
      iconName: "Boxes",
      labelKey: "nav.mgmt.inventory",
      label: "Inventory",
      requires: { domain: "inventory", access: "c" },
    },
    {
      id: "mgmt-procurement",
      portal: "management",
      path: "/management/procurement",
      section: "domains",
      order: 40,
      iconName: "ShoppingCart",
      labelKey: "nav.mgmt.procurement",
      label: "Procurement",
      requires: { domain: "procurement", access: "c" },
    },
    {
      id: "mgmt-operations",
      portal: "management",
      path: "/management/operations/incidents",
      section: "domains",
      order: 50,
      iconName: "Settings",
      labelKey: "nav.mgmt.operations",
      label: "Operations",
      requires: { domain: "ops", access: "c" },
    },
    {
      id: "mgmt-maintenance",
      portal: "management",
      path: "/management/maintenance/orders",
      section: "domains",
      order: 60,
      iconName: "Wrench",
      labelKey: "nav.mgmt.maintenance",
      label: "Maintenance",
      requires: { domain: "maintenance", access: "c" },
    },
    {
      id: "mgmt-marketing",
      portal: "management",
      path: "/management/marketing/campaigns",
      section: "domains",
      order: 70,
      iconName: "Megaphone",
      labelKey: "nav.mgmt.marketing",
      label: "Marketing",
      requires: { domain: "marketing", access: "c" },
    },

    // ── Management · Shared section ──
    {
      id: "mgmt-reports",
      portal: "management",
      path: "/management/reports",
      section: "shared",
      order: 10,
      iconName: "FileText",
      labelKey: "nav.mgmt.reports",
      label: "Reports",
      requires: { domain: "reports", access: "r" },
    },
    {
      id: "mgmt-audit",
      portal: "management",
      path: "/management/audit",
      section: "shared",
      order: 20,
      iconName: "History",
      labelKey: "nav.mgmt.audit",
      label: "Audit Log",
      requires: { domain: "reports", access: "r" },
    },
    {
      id: "mgmt-announcements",
      portal: "management",
      path: "/management/announcements",
      section: "shared",
      order: 30,
      iconName: "Megaphone",
      labelKey: "nav.mgmt.announcements",
      label: "Announcements",
      requires: { domain: "comms", access: "r" },
    },
    // mgmt-attendance → owned by src/features/attendance/nav.ts
    {
      id: "mgmt-staffing",
      portal: "management",
      path: "/management/staffing",
      section: "shared",
      order: 50,
      iconName: "UsersRound",
      labelKey: "nav.mgmt.staffing",
      label: "Staffing",
      requires: { domain: "hr", access: "r" },
    },
    {
      id: "mgmt-settings",
      portal: "management",
      path: "/management/settings",
      section: "shared",
      order: 60,
      iconName: "Settings",
      labelKey: "nav.mgmt.settings",
      label: "Settings",
      // Always visible.
    },

    // ── Crew · Role section ──
    {
      id: "crew-pos",
      portal: "crew",
      path: "/crew/pos",
      section: "role",
      order: 10,
      iconName: "CreditCard",
      labelKey: "nav.crew.pos",
      label: "POS Terminal",
      requires: { domain: "pos", access: "c" },
    },
    {
      id: "crew-active-orders",
      portal: "crew",
      path: "/crew/active-orders",
      section: "role",
      order: 20,
      iconName: "Receipt",
      labelKey: "nav.crew.activeOrders",
      label: "Active Orders",
      requires: { domain: "pos", access: "r" },
    },
    {
      id: "crew-entry-validation",
      portal: "crew",
      path: "/crew/entry-validation",
      section: "role",
      order: 30,
      iconName: "QrCode",
      labelKey: "nav.crew.entry",
      label: "Entry Validation",
      requires: { domain: "booking", access: "r" },
    },
    {
      id: "crew-restock",
      portal: "crew",
      path: "/crew/restock",
      section: "role",
      order: 40,
      iconName: "Package",
      labelKey: "nav.crew.restock",
      label: "Restock",
      requires: { domain: "inventory_ops", access: "c" },
    },
    {
      id: "crew-logistics",
      portal: "crew",
      path: "/crew/logistics/restock-queue",
      section: "role",
      order: 50,
      iconName: "Truck",
      labelKey: "nav.crew.logistics",
      label: "Logistics",
      requires: { domain: "inventory_ops", access: "c" },
    },
    {
      id: "crew-disposals",
      portal: "crew",
      path: "/crew/disposals",
      section: "role",
      order: 60,
      iconName: "Trash2",
      labelKey: "nav.crew.disposals",
      label: "Waste",
      requires: { domain: "inventory_ops", access: "c" },
    },
    {
      id: "crew-maintenance",
      portal: "crew",
      path: "/crew/maintenance/orders",
      section: "role",
      order: 70,
      iconName: "Wrench",
      labelKey: "nav.crew.workOrders",
      label: "Work Orders",
      requires: { domain: "maintenance", access: "c" },
    },

    // ── Crew · Shared section ──
    // crew-attendance → owned by src/features/attendance/nav.ts (order: 10)
    {
      id: "crew-schedule",
      portal: "crew",
      path: "/crew/schedule",
      section: "shared",
      order: 20,
      iconName: "CalendarDays",
      labelKey: "nav.crew.schedule",
      label: "Schedule",
      requires: { domain: "hr", access: "r" },
    },
    {
      id: "crew-leave",
      portal: "crew",
      path: "/crew/leave",
      section: "shared",
      order: 30,
      iconName: "CalendarOff",
      labelKey: "nav.crew.leave",
      label: "Leave",
      requires: { domain: "hr", access: "c" },
    },
    {
      id: "crew-incidents",
      portal: "crew",
      path: "/crew/incidents",
      section: "shared",
      order: 40,
      iconName: "Siren",
      labelKey: "nav.crew.incidents",
      label: "Incidents",
      // Always visible.
    },
    {
      id: "crew-zone-scan",
      portal: "crew",
      path: "/crew/zone-scan",
      section: "shared",
      order: 50,
      iconName: "ScanLine",
      labelKey: "nav.crew.zoneScan",
      label: "Zone Scan",
      // Always visible.
    },
    {
      id: "crew-feedback",
      portal: "crew",
      path: "/crew/feedback",
      section: "shared",
      order: 60,
      iconName: "MessageCircle",
      labelKey: "nav.crew.feedback",
      label: "Feedback",
      // Always visible.
    },
    {
      id: "crew-announcements",
      portal: "crew",
      path: "/crew/announcements",
      section: "shared",
      order: 70,
      iconName: "Megaphone",
      labelKey: "nav.crew.announcements",
      label: "Announcements",
      // Always visible.
    },
    {
      id: "crew-settings",
      portal: "crew",
      path: "/crew/settings",
      section: "shared",
      order: 80,
      iconName: "Settings",
      labelKey: "nav.crew.settings",
      label: "Settings",
      // Always visible.
    },
  ],
} as const;
